on: push
name: SonarQube
jobs:
  sonarQubeTrigger:
    name: SonarQube Trigger
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Setup sonarqube
      uses: warchant/setup-sonar-scanner@v3
  
    - name: Run sonarqube
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: sonar-scanner -X
       -Dsonar.projectKey=testando
       -Dsonar.sources=. 
       -Dsonar.host.url=http://179.232.143.216:9000
       -Dsonar.login=sqp_9ece2af8033853149e1f81f7601e2ad8f5500c29
