on: push
name: SonarQube
jobs:
  sonarQubeTrigger:
    name: SonarQube Trigger
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup sonarqube
      uses: sonarsource/sonarqube-scan-action@master
    - name: Run sonarqube
      run: sonar-scanner -X
       -Dsonar.projectKey=testando
       -Dsonar.sources=. 
       -Dsonar.host.url=http://localhost:9000 
       -Dsonar.login=sqp_9ece2af8033853149e1f81f7601e2ad8f5500c29
