on: push
name: SonarQube
jobs:
  sonarQubeTrigger:
    name: SonarQube Trigger
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Setup sonarqube
      uses: warchant/setup-sonar-scanner@v3
      
    - name: API
      run: 'curl -u sqp_9ece2af8033853149e1f81f7601e2ad8f5500c29: https://sonarqube.com/api/sqp_9ece2af8033853149e1f81f7601e2ad8f5500c29/search'
  
    - name: Run sonarqube
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: sonar-scanner -X
       -Dsonar.projectKey=testando
       -Dsonar.core.serverBaseURL=${{ secrets.SONAR_URL }}
       -Dsonar.sources=. 
       -Dsonar.login=sqp_9ece2af8033853149e1f81f7601e2ad8f5500c29
