on: push
name: SonarQube
jobs:
  sonarQubeTrigger:
    name: SonarQube Trigger
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Setup sonarqube
      uses: warchant/setup-sonar-scanner@v3
      
    - name: API
      run: ' curl -s -u admin:carboidrato2911 https://sonarqube.com/api/sqp_fe878e7ec800b45961a01cb452423cd5200e15f8/search'
      
    - name: Run sonarqube
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        LC_ALL: "ru_RU.UTF-8"
      run: sonar-scanner -X
       -Dsonar.projectKey=local
       -Dsonar.host.url=${{ secrets.SONAR_URL }}
       -Dsonar.sources=. 
       -Dsonar.login=sqp_fe878e7ec800b45961a01cb452423cd5200e15f8
    services:
      sonarqube:
        image: sonarqube:9.6-community
        ports:
          - 9000:9000   
