on: push
name: SonarQube
jobs:
  sonarQubeTrigger:
    name: SonarQube Trigger
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Setup sonarqube
      uses: warchant/setup-sonar-scanner@v3
      
    - name: API
      run: ' curl -s -u admin:carboidrato2911 http://localhost:9000/api/qualitygates/project_status?projectKey=local'
      
    - name: Run sonarqube
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        LC_ALL: "ru_RU.UTF-8"
      run: sonar-scanner -X
       -Dsonar.projectKey=local
       -Dsonar.host.url=${{ secrets.SONAR_URL }}
       -Dsonar.sources=. 
       -Dsonar.login=sqp_0ae53f233c581709d31888f8c98cf44018e51f0e
