name: QA

on: [push, pull_request]

jobs:
  run_qa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        env:
          token: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - run: run.sh
        timeout-minutes: 5
    services:
      sonarqube:
        image: sonarqube:9.6-community
        ports:
          - 9000:9000
